# Generated by Django 6.1.1 on 2026-10-07 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Estudiante',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='email',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='whatsapp',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='asistencia',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
